version: "2"
linters:
  enable:
    - bodyclose
    - durationcheck
    - errorlint
    - gosec
    - misspell
    - nilerr
    - prealloc
    - unconvert
    - unparam
    - wastedassign
  settings:
    gosec:
      excludes:
        - G104
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
