name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15, macos-15-intel, windows-latest]
        go: ["1.25.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build ./cmd/nodex/

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./...

      - name: Fmt check
        run: |
          diff=$(gofmt -s -d .)
          if [ -n "$diff" ]; then
            echo "$diff"
            exit 1
          fi
        shell: bash
